name: wallpapers381 # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '2.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Generates a wallpaper with text in them. # 79 char long summary
description: |
  Generates a wallpaper with text in them.
  This is aimed at teaching the users some important messages.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/wallpapers381 ./ubuntu
      go build -o $SNAPCRAFT_PART_INSTALL/bin/switch ./ubuntu_switch



apps:
  wallpapers381:
    command: bin/wallpapers381
    daemon: simple
    restart-condition: on-abnormal

  switch:
    command: bin/switch
    extensions: [gnome-3-38]
    plugs:
      - gsettings
